# Generated by Django 3.2.7 on 2021-10-25 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('street', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('ward', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ParkVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('moto', 'Xe máy'), ('car_4_7_seats', 'Xe 4-7 chỗ'), ('car_9_16_seats', 'Xe 9-16 chỗ'), ('container_truck', 'Xe container')], default=None, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('daytimePrice', models.IntegerField(default=0)),
                ('overnightPrice', models.IntegerField(default=0)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyParking.park')),
            ],
        ),
        migrations.CreateModel(
            name='ParkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyParking.park')),
            ],
        ),
    ]
