# Generated by Django 3.2.7 on 2021-10-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyParking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
